spring:
  application:
    name: develop

  # --------------------------------------------------------------------
  # NOTE: 프로젝트의 최상위 폴더에서 'docker-compose up -d' 실행 후 Spring Boot 실행
  # --------------------------------------------------------------------
  datasource:
     url: jdbc:postgresql://localhost:5432/tourai
     username: tourai
     password: tourai
     driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

  data:
    redis:
      host: localhost
      port: 6379